# Generated by Django 5.2.6 on 2025-10-03 02:34

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chapter_exercise_course_chapter_course'),
    ]

    operations = [
         migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=6, blank=True, null=True),
        ),
    ]
