# Generated by Django 5.2.6 on 2025-10-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_disabled',
        ),
    ]
