# Generated by Django 5.2.7 on 2025-10-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_certificate_speciality_certificateexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speciality'),
        ),
        migrations.CreateModel(
            name='CertificatExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('qcm', 'QCM'), ('truefalse', 'True/False'), ('text', 'Text')], max_length=20)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('option1', models.CharField(blank=True, max_length=200, null=True)),
                ('option2', models.CharField(blank=True, max_length=200, null=True)),
                ('option3', models.CharField(blank=True, max_length=200, null=True)),
                ('option4', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.certificate')),
            ],
        ),
        migrations.DeleteModel(
            name='CertificateExercise',
        ),
    ]
