# Generated by Django 5.2.7 on 2025-10-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_subscription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(help_text='e.g., 30 days, 3 months, 1 year', max_length=100),
        ),
    ]
