# Generated by Django 5.2.7 on 2025-10-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_certificate_speciality_certificatexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatexercise',
            name='exercise_type',
            field=models.CharField(choices=[('qcu', 'QCU'), ('truefalse', 'True/False'), ('text', 'Text')], max_length=20),
        ),
    ]
