# Generated by Django 5.2.6 on 2025-10-21 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coursecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.coursecategory'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
