# Generated by Django 5.2.7 on 2025-10-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_subscription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='Type of user this subscription is for', max_length=20),
        ),
    ]
