# Generated by Django 5.2.7 on 2025-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_certificatexercise_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_cover_images/'),
        ),
    ]
