# Generated by Django 5.2.6 on 2025-10-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_exercise_chapter_remove_course_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sublesson',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
