# Generated by Django 5.2.7 on 2025-10-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_certificate_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cover_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
