# Generated by Django 5.2.7 on 2025-10-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
