# Generated by Django 5.2.7 on 2025-10-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_exercise_chapter_remove_course_credits_and_more'),
        ('core', '0013_alter_user_role'),
    ]

    operations = [
    ]
