# Generated by Django 5.2.6 on 2025-10-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio'), ('external', 'External Link')], max_length=20),
        ),
    ]
