# Generated by Django 5.2.7 on 2025-10-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20251028_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='lesson',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='chapter_videos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='chapter_docs/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.chapter'),
            preserve_default=False,
        ),
    ]
