# Generated by Django 5.2.7 on 2025-10-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20251023_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField(default=0, help_text='Number of students (for teachers)')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_frequency', models.IntegerField(default=1, help_text='Days per week (1-7)')),
                ('course_count', models.IntegerField(default=0, help_text='Number of courses')),
                ('experience_level', models.IntegerField(default=1, help_text='1=Beginner, 5=Expert')),
                ('study_hours', models.DecimalField(decimal_places=1, default=0, help_text='Hours per day', max_digits=4)),
                ('needs_video', models.BooleanField(default=False)),
                ('needs_quiz', models.BooleanField(default=False)),
                ('needs_forum', models.BooleanField(default=False)),
                ('needs_analytics', models.BooleanField(default=False)),
                ('needs_certificates', models.BooleanField(default=False)),
                ('needs_offline', models.BooleanField(default=False)),
                ('needs_support', models.BooleanField(default=False)),
                ('goal_type', models.CharField(choices=[('professional', 'Professional Development'), ('academic', 'Academic Achievement'), ('personal', 'Personal Interest')], default='academic', max_length=20)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('university', 'University'), ('professional', 'Professional Training')], default='university', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='ML model confidence (0-100)', max_digits=5)),
                ('compatibility_score', models.DecimalField(decimal_places=2, help_text='Overall compatibility (0-100)', max_digits=5)),
                ('alternative_1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alternative_2_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user_action', models.CharField(choices=[('accepted', 'Accepted Recommendation'), ('alternative', 'Chose Alternative'), ('ignored', 'Ignored Recommendation'), ('pending', 'Pending Decision')], default='pending', max_length=20)),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('alternative_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt1_recommendations', to='core.subscription')),
                ('alternative_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt2_recommendations', to='core.subscription')),
                ('chosen_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_recommendations', to='core.subscription')),
                ('recommended_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_recommendations', to='core.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userpreference')),
            ],
            options={
                'verbose_name_plural': 'Recommendation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
