# Generated by Django 5.2.6 on 2025-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_resource_external_url_alter_resource_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_lessons',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_sublessons',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
