# Generated by Django 5.2.6 on 2025-10-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_max_lessons_lesson_max_sublessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
