# Generated by Django 5.2.7 on 2025-10-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_exercise_lesson_chapter_exercise_chapter'),
        ('core', '0016_course_publish_date'),
    ]

    operations = [
    ]
