# Generated by Django 5.2.7 on 2025-10-29 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20251029_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublesson_progress', to=settings.AUTH_USER_MODEL)),
                ('sub_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.sublesson')),
            ],
            options={
                'unique_together': {('student', 'sub_lesson')},
            },
        ),
    ]
