# Generated by Django 5.2.7 on 2025-10-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userpreference_recommendationhistory'),
        ('core', '0017_merge_20251030_0225'),
        ('core', '0018_sublessonprogress'),
    ]

    operations = [
    ]
