# Generated by Django 5.2.7 on 2025-10-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20251030_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
