# Generated by Django 5.2.7 on 2025-10-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_exercise_chapter_delete_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='max_sublessons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
