"""
Lifetime Value (LTV) calculator for users.
"""

import os
import joblib
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.ensemble import RandomForestRegressor
from django.conf import settings

from core.ml.features.feature_engineering import FeatureEngineer
from core.ml.utils.data_preprocessing import DataPreprocessor
from core.ml.utils.model_evaluator import ModelEvaluator


class LTVCalculator:
    """
    Calculate and predict user Lifetime Value (LTV).
    
    LTV = Total revenue generated by a user over their entire relationship.
    """
    
    MODEL_DIR = os.path.join(settings.BASE_DIR, 'core', 'ml', 'trained_models')
    MODEL_FILE = 'ltv_calculator.pkl'
    SCALER_FILE = 'ltv_scaler.pkl'
    METADATA_FILE = 'ltv_metadata.pkl'
    
    def __init__(self):
        """Initialize LTV calculator."""
        self.model = RandomForestRegressor(
            n_estimators=100,
            max_depth=10,
            random_state=42,
            n_jobs=-1
        )
        self.preprocessor = DataPreprocessor(scaling_method='standard')
        self.feature_engineer = FeatureEngineer()
        self.is_trained = False
        self.metadata = {}
        
        os.makedirs(self.MODEL_DIR, exist_ok=True)
    
    def train(self):
        """
        Train the LTV prediction model.
        
        Returns:
            dict: Training metrics
        """
        print("Creating LTV training dataset...")
        df = self.feature_engineer.create_training_dataset(include_churned=True)
        
        if df.empty or len(df) < 5:
            raise ValueError("Insufficient data for training. Need at least 5 samples.")
        
        print(f"Dataset created: {len(df)} samples")
        
        # Target is total_spent (actual LTV so far)
        X = self.feature_engineer.prepare_features_for_prediction(df)
        y = df['total_spent'].values
        
        # Remove users with zero spending
        mask = y > 0
        X = X[mask]
        y = y[mask]
        
        if len(X) < 5:
            raise ValueError("Insufficient data with positive LTV.")
        
        # Split data
        X_train, X_test, y_train, y_test = DataPreprocessor.split_data(
            X, y, test_size=0.2
        )
        
        # Scale features
        print("Scaling features...")
        X_train_scaled = self.preprocessor.fit_transform(X_train)
        X_test_scaled = self.preprocessor.transform(X_test)
        
        # Train model
        print("Training model...")
        self.model.fit(X_train_scaled, y_train)
        self.is_trained = True
        
        # Evaluate
        print("Evaluating model...")
        y_pred = self.model.predict(X_test_scaled)
        
        metrics = ModelEvaluator.evaluate_regression(y_test, y_pred)
        
        # Feature importance
        if hasattr(self.model, 'feature_importances_'):
            feature_names = self.feature_engineer.get_feature_importance_names()
            importances = self.model.feature_importances_
            indices = np.argsort(importances)[::-1]
            metrics['feature_importance'] = {
                feature_names[i]: float(importances[i])
                for i in indices[:10]
            }
        
        # Save metadata
        self.metadata = {
            'trained_at': datetime.now().isoformat(),
            'n_samples': len(df),
            'n_features': X.shape[1],
            'metrics': metrics,
            'feature_names': self.feature_engineer.get_feature_importance_names()
        }
        
        print(f"\nTraining completed!")
        print(f"R² Score: {metrics['r2_score']:.3f}")
        print(f"MAE: ${metrics['mae']:.2f}")
        
        return metrics
    
    def predict_ltv(self, subscription):
        """
        Predict LTV for a subscription.
        
        Args:
            subscription: UserSubscription instance
            
        Returns:
            dict: LTV prediction
        """
        if not self.is_trained:
            self.load()
        
        # Extract features
        features = self.feature_engineer.extract_subscription_features(subscription)
        
        # Prepare for prediction
        feature_names = self.feature_engineer.get_feature_importance_names()
        X = pd.DataFrame([features])[feature_names].fillna(0)
        X = X.replace([np.inf, -np.inf], 0)
        
        # Scale features
        X_scaled = self.preprocessor.transform(X)
        
        # Predict
        predicted_ltv = self.model.predict(X_scaled)[0]
        current_ltv = features['total_spent']
        
        # Calculate metrics
        ltv_potential = max(predicted_ltv - current_ltv, 0)
        
        return {
            'subscription_id': subscription.id,
            'user_id': subscription.user.id,
            'current_ltv': float(current_ltv),
            'predicted_ltv': float(predicted_ltv),
            'ltv_potential': float(ltv_potential),
            'predicted_at': datetime.now().isoformat()
        }
    
    def calculate_cohort_ltv(self, cohort_month=None):
        """
        Calculate average LTV by cohort.
        
        Args:
            cohort_month: Specific month to analyze (YYYY-MM)
            
        Returns:
            dict: Cohort LTV statistics
        """
        df = self.feature_engineer.create_training_dataset(include_churned=True)
        
        if df.empty:
            return {}
        
        # Group by signup month
        df['cohort'] = pd.to_datetime(df['signup_month'], format='%m').dt.month_name()
        
        cohort_stats = df.groupby('cohort').agg({
            'total_spent': ['mean', 'median', 'sum', 'count']
        }).round(2)
        
        return cohort_stats.to_dict()
    
    def get_ltv_segments(self):
        """
        Segment users by LTV.
        
        Returns:
            dict: LTV segments
        """
        df = self.feature_engineer.create_training_dataset(include_churned=True)
        
        if df.empty:
            return {}
        
        # Define segments
        df['ltv_segment'] = pd.cut(
            df['total_spent'],
            bins=[0, 50, 150, 500, float('inf')],
            labels=['Low', 'Medium', 'High', 'Premium']
        )
        
        segments = df.groupby('ltv_segment').agg({
            'subscription_id': 'count',
            'total_spent': ['mean', 'sum']
        }).round(2)
        
        return segments.to_dict()
    
    def save(self):
        """Save trained model to disk."""
        if not self.is_trained:
            raise ValueError("Model not trained yet.")
        
        model_path = os.path.join(self.MODEL_DIR, self.MODEL_FILE)
        scaler_path = os.path.join(self.MODEL_DIR, self.SCALER_FILE)
        metadata_path = os.path.join(self.MODEL_DIR, self.METADATA_FILE)
        
        joblib.dump(self.model, model_path)
        joblib.dump(self.preprocessor, scaler_path)
        joblib.dump(self.metadata, metadata_path)
        
        print(f"Model saved to {model_path}")
    
    def load(self):
        """Load trained model from disk."""
        model_path = os.path.join(self.MODEL_DIR, self.MODEL_FILE)
        scaler_path = os.path.join(self.MODEL_DIR, self.SCALER_FILE)
        metadata_path = os.path.join(self.MODEL_DIR, self.METADATA_FILE)
        
        if not os.path.exists(model_path):
            raise FileNotFoundError(
                f"Model file not found: {model_path}. Train the model first."
            )
        
        self.model = joblib.load(model_path)
        self.preprocessor = joblib.load(scaler_path)
        self.metadata = joblib.load(metadata_path)
        self.is_trained = True
        
        print(f"Model loaded from {model_path}")
