# Generated by Django 5.2.7 on 2025-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
