# Generated by Django 5.2.7 on 2025-10-27 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeetude',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='groupes_rejoints', to=settings.AUTH_USER_MODEL),
        ),
    ]
